### ISSUE TITLE
Learn X the hard way

### ISSUE THREAD

**Issue by computermouth** [rylev/learn-rust-the-hard-way#10]
I'm having a hard time getting a copy of this, I found the git repository where it lives, but I'm having trouble getting around to building it.

Anyways, I'd love to help expand/update/learn this material. It'd be cool if I could also get a copy of Learn X the Hard Way.

**Comment by rylev** [comment]
Awesome. I too would like to pick this up again. I was using http://c.learncodethehardway.org/book/ as a reference.
