### ISSUE TITLE
Pad exercise numbers for consistency.

### ISSUE THREAD

**Issue by sinistersnare** [rylev/learn-rust-the-hard-way#3]
If you look at the repo on github, the files are ordered as such:

* 1.rs
* 10.rs
* 11.rs.
* ...
* 2.rs

To make them be in the correct order (1, 2, 3, 4...) then you need to pad the numbers with 0's as such:

* 001.rs
* 002.rs
* 003.rs
* ...
* 010.rs

This will be very helpful when look at the github repo, as its more organized. Thanks!

**Comment by shantanu69** [comment]
Does this work. #9

**Comment by sinistersnare** [comment]
:+1:

**Comment by shantanu404** [comment]
@sinistersnare How about closing the issue now? All sorted! :smile:

**Comment by sinistersnare** [comment]
Sorry, was not on Github at all throughout the semester. Thanks for the change!
